interface CountryCode {
  code: string;
  country: string;
  short: string;
  flag: string;
  minLength: number;
  maxLength: number;
}

const countryCodes: CountryCode[] = [
  // A
  {
    code: "+93",
    country: "Afghanistan",
    short: "AF",
    flag: "🇦🇫",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+355",
    country: "Albania",
    short: "AL",
    flag: "🇦🇱",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+213",
    country: "Algeria",
    short: "DZ",
    flag: "🇩🇿",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+1684",
    country: "American Samoa",
    short: "AS",
    flag: "🇦🇸",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+376",
    country: "Andorra",
    short: "AD",
    flag: "🇦🇩",
    minLength: 6,
    maxLength: 6,
  },
  {
    code: "+244",
    country: "Angola",
    short: "AO",
    flag: "🇦🇴",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+1264",
    country: "Anguilla",
    short: "AI",
    flag: "🇦🇮",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+672",
    country: "Antarctica",
    short: "AQ",
    flag: "🇦🇶",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+1268",
    country: "Antigua and Barbuda",
    short: "AG",
    flag: "🇦🇬",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+54",
    country: "Argentina",
    short: "AR",
    flag: "🇦🇷",
    minLength: 10,
    maxLength: 11,
  },
  {
    code: "+374",
    country: "Armenia",
    short: "AM",
    flag: "🇦🇲",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+297",
    country: "Aruba",
    short: "AW",
    flag: "🇦🇼",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+61",
    country: "Australia",
    short: "AU",
    flag: "🇦🇺",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+43",
    country: "Austria",
    short: "AT",
    flag: "🇦🇹",
    minLength: 10,
    maxLength: 12,
  },
  {
    code: "+994",
    country: "Azerbaijan",
    short: "AZ",
    flag: "🇦🇿",
    minLength: 9,
    maxLength: 9,
  },

  // B
  {
    code: "+1242",
    country: "Bahamas",
    short: "BS",
    flag: "🇧🇸",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+973",
    country: "Bahrain",
    short: "BH",
    flag: "🇧🇭",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+880",
    country: "Bangladesh",
    short: "BD",
    flag: "🇧🇩",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+1246",
    country: "Barbados",
    short: "BB",
    flag: "🇧🇧",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+375",
    country: "Belarus",
    short: "BY",
    flag: "🇧🇾",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+32",
    country: "Belgium",
    short: "BE",
    flag: "🇧🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+501",
    country: "Belize",
    short: "BZ",
    flag: "🇧🇿",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+229",
    country: "Benin",
    short: "BJ",
    flag: "🇧🇯",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+1441",
    country: "Bermuda",
    short: "BM",
    flag: "🇧🇲",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+975",
    country: "Bhutan",
    short: "BT",
    flag: "🇧🇹",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+591",
    country: "Bolivia",
    short: "BO",
    flag: "🇧🇴",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+387",
    country: "Bosnia and Herzegovina",
    short: "BA",
    flag: "🇧🇦",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+267",
    country: "Botswana",
    short: "BW",
    flag: "🇧🇼",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+55",
    country: "Brazil",
    short: "BR",
    flag: "🇧🇷",
    minLength: 10,
    maxLength: 11,
  },
  {
    code: "+246",
    country: "British Indian Ocean Territory",
    short: "IO",
    flag: "🇮🇴",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+1284",
    country: "British Virgin Islands",
    short: "VG",
    flag: "🇻🇬",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+673",
    country: "Brunei",
    short: "BN",
    flag: "🇧🇳",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+359",
    country: "Bulgaria",
    short: "BG",
    flag: "🇧🇬",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+226",
    country: "Burkina Faso",
    short: "BF",
    flag: "🇧🇫",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+257",
    country: "Burundi",
    short: "BI",
    flag: "🇧🇮",
    minLength: 8,
    maxLength: 8,
  },

  // C
  {
    code: "+855",
    country: "Cambodia",
    short: "KH",
    flag: "🇰🇭",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+237",
    country: "Cameroon",
    short: "CM",
    flag: "🇨🇲",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+1",
    country: "Canada",
    short: "CA",
    flag: "🇨🇦",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+238",
    country: "Cape Verde",
    short: "CV",
    flag: "🇨🇻",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+1345",
    country: "Cayman Islands",
    short: "KY",
    flag: "🇰🇾",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+236",
    country: "Central African Republic",
    short: "CF",
    flag: "🇨🇫",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+235",
    country: "Chad",
    short: "TD",
    flag: "🇹🇩",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+56",
    country: "Chile",
    short: "CL",
    flag: "🇨🇱",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+86",
    country: "China",
    short: "CN",
    flag: "🇨🇳",
    minLength: 11,
    maxLength: 11,
  },
  {
    code: "+61",
    country: "Christmas Island",
    short: "CX",
    flag: "🇨🇽",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+61",
    country: "Cocos Islands",
    short: "CC",
    flag: "🇨🇨",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+57",
    country: "Colombia",
    short: "CO",
    flag: "🇨🇴",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+269",
    country: "Comoros",
    short: "KM",
    flag: "🇰🇲",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+682",
    country: "Cook Islands",
    short: "CK",
    flag: "🇨🇰",
    minLength: 5,
    maxLength: 5,
  },
  {
    code: "+506",
    country: "Costa Rica",
    short: "CR",
    flag: "🇨🇷",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+385",
    country: "Croatia",
    short: "HR",
    flag: "🇭🇷",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+53",
    country: "Cuba",
    short: "CU",
    flag: "🇨🇺",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+599",
    country: "Curacao",
    short: "CW",
    flag: "🇨🇼",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+357",
    country: "Cyprus",
    short: "CY",
    flag: "🇨🇾",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+420",
    country: "Czech Republic",
    short: "CZ",
    flag: "🇨🇿",
    minLength: 9,
    maxLength: 9,
  },

  // D
  {
    code: "+243",
    country: "Democratic Republic of the Congo",
    short: "CD",
    flag: "🇨🇩",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+45",
    country: "Denmark",
    short: "DK",
    flag: "🇩🇰",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+253",
    country: "Djibouti",
    short: "DJ",
    flag: "🇩🇯",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+1767",
    country: "Dominica",
    short: "DM",
    flag: "🇩🇲",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+1",
    country: "Dominican Republic",
    short: "DO",
    flag: "🇩🇴",
    minLength: 10,
    maxLength: 10,
  },

  // E
  {
    code: "+593",
    country: "Ecuador",
    short: "EC",
    flag: "🇪🇨",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+20",
    country: "Egypt",
    short: "EG",
    flag: "🇪🇬",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+503",
    country: "El Salvador",
    short: "SV",
    flag: "🇸🇻",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+240",
    country: "Equatorial Guinea",
    short: "GQ",
    flag: "🇬🇶",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+291",
    country: "Eritrea",
    short: "ER",
    flag: "🇪🇷",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+372",
    country: "Estonia",
    short: "EE",
    flag: "🇪🇪",
    minLength: 7,
    maxLength: 8,
  },
  {
    code: "+268",
    country: "Eswatini",
    short: "SZ",
    flag: "🇸🇿",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+251",
    country: "Ethiopia",
    short: "ET",
    flag: "🇪🇹",
    minLength: 9,
    maxLength: 9,
  },

  // F
  {
    code: "+500",
    country: "Falkland Islands",
    short: "FK",
    flag: "🇫🇰",
    minLength: 5,
    maxLength: 5,
  },
  {
    code: "+298",
    country: "Faroe Islands",
    short: "FO",
    flag: "🇫🇴",
    minLength: 6,
    maxLength: 6,
  },
  {
    code: "+679",
    country: "Fiji",
    short: "FJ",
    flag: "🇫🇯",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+358",
    country: "Finland",
    short: "FI",
    flag: "🇫🇮",
    minLength: 9,
    maxLength: 10,
  },
  {
    code: "+33",
    country: "France",
    short: "FR",
    flag: "🇫🇷",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+594",
    country: "French Guiana",
    short: "GF",
    flag: "🇬🇫",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+689",
    country: "French Polynesia",
    short: "PF",
    flag: "🇵🇫",
    minLength: 8,
    maxLength: 8,
  },

  // G
  {
    code: "+241",
    country: "Gabon",
    short: "GA",
    flag: "🇬🇦",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+220",
    country: "Gambia",
    short: "GM",
    flag: "🇬🇲",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+995",
    country: "Georgia",
    short: "GE",
    flag: "🇬🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+49",
    country: "Germany",
    short: "DE",
    flag: "🇩🇪",
    minLength: 10,
    maxLength: 12,
  },
  {
    code: "+233",
    country: "Ghana",
    short: "GH",
    flag: "🇬🇭",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+350",
    country: "Gibraltar",
    short: "GI",
    flag: "🇬🇮",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+30",
    country: "Greece",
    short: "GR",
    flag: "🇬🇷",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+299",
    country: "Greenland",
    short: "GL",
    flag: "🇬🇱",
    minLength: 6,
    maxLength: 6,
  },
  {
    code: "+1473",
    country: "Grenada",
    short: "GD",
    flag: "🇬🇩",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+590",
    country: "Guadeloupe",
    short: "GP",
    flag: "🇬🇵",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+1671",
    country: "Guam",
    short: "GU",
    flag: "🇬🇺",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+502",
    country: "Guatemala",
    short: "GT",
    flag: "🇬🇹",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+44",
    country: "Guernsey",
    short: "GG",
    flag: "🇬🇬",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+224",
    country: "Guinea",
    short: "GN",
    flag: "🇬🇳",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+245",
    country: "Guinea-Bissau",
    short: "GW",
    flag: "🇬🇼",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+592",
    country: "Guyana",
    short: "GY",
    flag: "🇬🇾",
    minLength: 7,
    maxLength: 7,
  },

  // H
  {
    code: "+509",
    country: "Haiti",
    short: "HT",
    flag: "🇭🇹",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+504",
    country: "Honduras",
    short: "HN",
    flag: "🇭🇳",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+852",
    country: "Hong Kong",
    short: "HK",
    flag: "🇭🇰",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+36",
    country: "Hungary",
    short: "HU",
    flag: "🇭🇺",
    minLength: 9,
    maxLength: 9,
  },

  // I
  {
    code: "+354",
    country: "Iceland",
    short: "IS",
    flag: "🇮🇸",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+91",
    country: "India",
    short: "IN",
    flag: "🇮🇳",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+62",
    country: "Indonesia",
    short: "ID",
    flag: "🇮🇩",
    minLength: 9,
    maxLength: 11,
  },
  {
    code: "+98",
    country: "Iran",
    short: "IR",
    flag: "🇮🇷",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+964",
    country: "Iraq",
    short: "IQ",
    flag: "🇮🇶",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+353",
    country: "Ireland",
    short: "IE",
    flag: "🇮🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+44",
    country: "Isle of Man",
    short: "IM",
    flag: "🇮🇲",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+972",
    country: "Israel",
    short: "IL",
    flag: "🇮🇱",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+39",
    country: "Italy",
    short: "IT",
    flag: "🇮🇹",
    minLength: 9,
    maxLength: 10,
  },
  {
    code: "+225",
    country: "Ivory Coast",
    short: "CI",
    flag: "🇨🇮",
    minLength: 10,
    maxLength: 10,
  },

  // J
  {
    code: "+1876",
    country: "Jamaica",
    short: "JM",
    flag: "🇯🇲",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+81",
    country: "Japan",
    short: "JP",
    flag: "🇯🇵",
    minLength: 10,
    maxLength: 11,
  },
  {
    code: "+44",
    country: "Jersey",
    short: "JE",
    flag: "🇯🇪",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+962",
    country: "Jordan",
    short: "JO",
    flag: "🇯🇴",
    minLength: 9,
    maxLength: 9,
  },

  // K
  {
    code: "+7",
    country: "Kazakhstan",
    short: "KZ",
    flag: "🇰🇿",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+254",
    country: "Kenya",
    short: "KE",
    flag: "🇰🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+686",
    country: "Kiribati",
    short: "KI",
    flag: "🇰🇮",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+383",
    country: "Kosovo",
    short: "XK",
    flag: "🇽🇰",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+965",
    country: "Kuwait",
    short: "KW",
    flag: "🇰🇼",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+996",
    country: "Kyrgyzstan",
    short: "KG",
    flag: "🇰🇬",
    minLength: 9,
    maxLength: 9,
  },

  // L
  {
    code: "+856",
    country: "Laos",
    short: "LA",
    flag: "🇱🇦",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+371",
    country: "Latvia",
    short: "LV",
    flag: "🇱🇻",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+961",
    country: "Lebanon",
    short: "LB",
    flag: "🇱🇧",
    minLength: 7,
    maxLength: 8,
  },
  {
    code: "+266",
    country: "Lesotho",
    short: "LS",
    flag: "🇱🇸",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+231",
    country: "Liberia",
    short: "LR",
    flag: "🇱🇷",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+218",
    country: "Libya",
    short: "LY",
    flag: "🇱🇾",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+423",
    country: "Liechtenstein",
    short: "LI",
    flag: "🇱🇮",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+370",
    country: "Lithuania",
    short: "LT",
    flag: "🇱🇹",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+352",
    country: "Luxembourg",
    short: "LU",
    flag: "🇱🇺",
    minLength: 9,
    maxLength: 9,
  },

  // M
  {
    code: "+853",
    country: "Macao",
    short: "MO",
    flag: "🇲🇴",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+389",
    country: "Macedonia",
    short: "MK",
    flag: "🇲🇰",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+261",
    country: "Madagascar",
    short: "MG",
    flag: "🇲🇬",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+265",
    country: "Malawi",
    short: "MW",
    flag: "🇲🇼",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+60",
    country: "Malaysia",
    short: "MY",
    flag: "🇲🇾",
    minLength: 9,
    maxLength: 10,
  },
  {
    code: "+960",
    country: "Maldives",
    short: "MV",
    flag: "🇲🇻",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+223",
    country: "Mali",
    short: "ML",
    flag: "🇲🇱",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+356",
    country: "Malta",
    short: "MT",
    flag: "🇲🇹",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+692",
    country: "Marshall Islands",
    short: "MH",
    flag: "🇲🇭",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+596",
    country: "Martinique",
    short: "MQ",
    flag: "🇲🇶",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+222",
    country: "Mauritania",
    short: "MR",
    flag: "🇲🇷",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+230",
    country: "Mauritius",
    short: "MU",
    flag: "🇲🇺",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+262",
    country: "Mayotte",
    short: "YT",
    flag: "🇾🇹",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+52",
    country: "Mexico",
    short: "MX",
    flag: "🇲🇽",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+691",
    country: "Micronesia",
    short: "FM",
    flag: "🇫🇲",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+373",
    country: "Moldova",
    short: "MD",
    flag: "🇲🇩",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+377",
    country: "Monaco",
    short: "MC",
    flag: "🇲🇨",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+976",
    country: "Mongolia",
    short: "MN",
    flag: "🇲🇳",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+382",
    country: "Montenegro",
    short: "ME",
    flag: "🇲🇪",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+1664",
    country: "Montserrat",
    short: "MS",
    flag: "🇲🇸",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+212",
    country: "Morocco",
    short: "MA",
    flag: "🇲🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+258",
    country: "Mozambique",
    short: "MZ",
    flag: "🇲🇿",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+95",
    country: "Myanmar",
    short: "MM",
    flag: "🇲🇲",
    minLength: 9,
    maxLength: 10,
  },

  // N
  {
    code: "+264",
    country: "Namibia",
    short: "NA",
    flag: "🇳🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+674",
    country: "Nauru",
    short: "NR",
    flag: "🇳🇷",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+977",
    country: "Nepal",
    short: "NP",
    flag: "🇳🇵",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+31",
    country: "Netherlands",
    short: "NL",
    flag: "🇳🇱",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+687",
    country: "New Caledonia",
    short: "NC",
    flag: "🇳🇨",
    minLength: 6,
    maxLength: 6,
  },
  {
    code: "+64",
    country: "New Zealand",
    short: "NZ",
    flag: "🇳🇿",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+505",
    country: "Nicaragua",
    short: "NI",
    flag: "🇳🇮",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+227",
    country: "Niger",
    short: "NE",
    flag: "🇳🇪",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+234",
    country: "Nigeria",
    short: "NG",
    flag: "🇳🇬",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+683",
    country: "Niue",
    short: "NU",
    flag: "🇳🇺",
    minLength: 4,
    maxLength: 4,
  },
  {
    code: "+672",
    country: "Norfolk Island",
    short: "NF",
    flag: "🇳🇫",
    minLength: 5,
    maxLength: 5,
  },
  {
    code: "+850",
    country: "North Korea",
    short: "KP",
    flag: "🇰🇵",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+1670",
    country: "Northern Mariana Islands",
    short: "MP",
    flag: "🇲🇵",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+47",
    country: "Norway",
    short: "NO",
    flag: "🇳🇴",
    minLength: 8,
    maxLength: 8,
  },

  // O
  {
    code: "+968",
    country: "Oman",
    short: "OM",
    flag: "🇴🇲",
    minLength: 8,
    maxLength: 8,
  },

  // P
  {
    code: "+92",
    country: "Pakistan",
    short: "PK",
    flag: "🇵🇰",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+680",
    country: "Palau",
    short: "PW",
    flag: "🇵🇼",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+970",
    country: "Palestine",
    short: "PS",
    flag: "🇵🇸",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+507",
    country: "Panama",
    short: "PA",
    flag: "🇵🇦",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+675",
    country: "Papua New Guinea",
    short: "PG",
    flag: "🇵🇬",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+595",
    country: "Paraguay",
    short: "PY",
    flag: "🇵🇾",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+51",
    country: "Peru",
    short: "PE",
    flag: "🇵🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+63",
    country: "Philippines",
    short: "PH",
    flag: "🇵🇭",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+64",
    country: "Pitcairn",
    short: "PN",
    flag: "🇵🇳",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+48",
    country: "Poland",
    short: "PL",
    flag: "🇵🇱",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+351",
    country: "Portugal",
    short: "PT",
    flag: "🇵🇹",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+1787",
    country: "Puerto Rico",
    short: "PR",
    flag: "🇵🇷",
    minLength: 10,
    maxLength: 10,
  },

  // Q
  {
    code: "+974",
    country: "Qatar",
    short: "QA",
    flag: "🇶🇦",
    minLength: 8,
    maxLength: 8,
  },

  // R
  {
    code: "+242",
    country: "Republic of the Congo",
    short: "CG",
    flag: "🇨🇬",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+262",
    country: "Reunion",
    short: "RE",
    flag: "🇷🇪",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+40",
    country: "Romania",
    short: "RO",
    flag: "🇷🇴",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+7",
    country: "Russia",
    short: "RU",
    flag: "🇷🇺",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+250",
    country: "Rwanda",
    short: "RW",
    flag: "🇷🇼",
    minLength: 9,
    maxLength: 9,
  },

  // S
  {
    code: "+290",
    country: "Saint Helena",
    short: "SH",
    flag: "🇸🇭",
    minLength: 4,
    maxLength: 4,
  },
  {
    code: "+1869",
    country: "Saint Kitts and Nevis",
    short: "KN",
    flag: "🇰🇳",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+1758",
    country: "Saint Lucia",
    short: "LC",
    flag: "🇱🇨",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+508",
    country: "Saint Pierre and Miquelon",
    short: "PM",
    flag: "🇵🇲",
    minLength: 6,
    maxLength: 6,
  },
  {
    code: "+1784",
    country: "Saint Vincent and the Grenadines",
    short: "VC",
    flag: "🇻🇨",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+685",
    country: "Samoa",
    short: "WS",
    flag: "🇼🇸",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+378",
    country: "San Marino",
    short: "SM",
    flag: "🇸🇲",
    minLength: 8,
    maxLength: 10,
  },
  {
    code: "+239",
    country: "Sao Tome and Principe",
    short: "ST",
    flag: "🇸🇹",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+966",
    country: "Saudi Arabia",
    short: "SA",
    flag: "🇸🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+221",
    country: "Senegal",
    short: "SN",
    flag: "🇸🇳",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+381",
    country: "Serbia",
    short: "RS",
    flag: "🇷🇸",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+248",
    country: "Seychelles",
    short: "SC",
    flag: "🇸🇨",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+232",
    country: "Sierra Leone",
    short: "SL",
    flag: "🇸🇱",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+65",
    country: "Singapore",
    short: "SG",
    flag: "🇸🇬",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+1721",
    country: "Sint Maarten",
    short: "SX",
    flag: "🇸🇽",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+421",
    country: "Slovakia",
    short: "SK",
    flag: "🇸🇰",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+386",
    country: "Slovenia",
    short: "SI",
    flag: "🇸🇮",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+677",
    country: "Solomon Islands",
    short: "SB",
    flag: "🇸🇧",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+252",
    country: "Somalia",
    short: "SO",
    flag: "🇸🇴",
    minLength: 8,
    maxLength: 9,
  },
  {
    code: "+27",
    country: "South Africa",
    short: "ZA",
    flag: "🇿🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+82",
    country: "South Korea",
    short: "KR",
    flag: "🇰🇷",
    minLength: 9,
    maxLength: 10,
  },
  {
    code: "+211",
    country: "South Sudan",
    short: "SS",
    flag: "🇸🇸",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+34",
    country: "Spain",
    short: "ES",
    flag: "🇪🇸",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+94",
    country: "Sri Lanka",
    short: "LK",
    flag: "🇱🇰",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+249",
    country: "Sudan",
    short: "SD",
    flag: "🇸🇩",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+597",
    country: "Suriname",
    short: "SR",
    flag: "🇸🇷",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+47",
    country: "Svalbard and Jan Mayen",
    short: "SJ",
    flag: "🇸🇯",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+46",
    country: "Sweden",
    short: "SE",
    flag: "🇸🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+41",
    country: "Switzerland",
    short: "CH",
    flag: "🇨🇭",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+963",
    country: "Syria",
    short: "SY",
    flag: "🇸🇾",
    minLength: 9,
    maxLength: 9,
  },

  // T
  {
    code: "+886",
    country: "Taiwan",
    short: "TW",
    flag: "🇹🇼",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+992",
    country: "Tajikistan",
    short: "TJ",
    flag: "🇹🇯",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+255",
    country: "Tanzania",
    short: "TZ",
    flag: "🇹🇿",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+66",
    country: "Thailand",
    short: "TH",
    flag: "🇹🇭",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+670",
    country: "Timor-Leste",
    short: "TL",
    flag: "🇹🇱",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+228",
    country: "Togo",
    short: "TG",
    flag: "🇹🇬",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+690",
    country: "Tokelau",
    short: "TK",
    flag: "🇹🇰",
    minLength: 4,
    maxLength: 4,
  },
  {
    code: "+676",
    country: "Tonga",
    short: "TO",
    flag: "🇹🇴",
    minLength: 5,
    maxLength: 5,
  },
  {
    code: "+1868",
    country: "Trinidad and Tobago",
    short: "TT",
    flag: "🇹🇹",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+216",
    country: "Tunisia",
    short: "TN",
    flag: "🇹🇳",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+90",
    country: "Turkey",
    short: "TR",
    flag: "🇹🇷",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+993",
    country: "Turkmenistan",
    short: "TM",
    flag: "🇹🇲",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+1649",
    country: "Turks and Caicos Islands",
    short: "TC",
    flag: "🇹🇨",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+688",
    country: "Tuvalu",
    short: "TV",
    flag: "🇹🇻",
    minLength: 5,
    maxLength: 5,
  },

  // U
  {
    code: "+256",
    country: "Uganda",
    short: "UG",
    flag: "🇺🇬",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+380",
    country: "Ukraine",
    short: "UA",
    flag: "🇺🇦",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+971",
    country: "United Arab Emirates",
    short: "AE",
    flag: "🇦🇪",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+44",
    country: "United Kingdom",
    short: "GB",
    flag: "🇬🇧",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+1",
    country: "United States",
    short: "US",
    flag: "🇺🇸",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+598",
    country: "Uruguay",
    short: "UY",
    flag: "🇺🇾",
    minLength: 8,
    maxLength: 8,
  },
  {
    code: "+1340",
    country: "US Virgin Islands",
    short: "VI",
    flag: "🇻🇮",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+998",
    country: "Uzbekistan",
    short: "UZ",
    flag: "🇺🇿",
    minLength: 9,
    maxLength: 9,
  },

  // V
  {
    code: "+678",
    country: "Vanuatu",
    short: "VU",
    flag: "🇻🇺",
    minLength: 7,
    maxLength: 7,
  },
  {
    code: "+379",
    country: "Vatican",
    short: "VA",
    flag: "🇻🇦",
    minLength: 8,
    maxLength: 10,
  },
  {
    code: "+58",
    country: "Venezuela",
    short: "VE",
    flag: "🇻🇪",
    minLength: 10,
    maxLength: 10,
  },
  {
    code: "+84",
    country: "Vietnam",
    short: "VN",
    flag: "🇻🇳",
    minLength: 9,
    maxLength: 10,
  },

  // W
  {
    code: "+681",
    country: "Wallis and Futuna",
    short: "WF",
    flag: "🇼🇫",
    minLength: 6,
    maxLength: 6,
  },
  {
    code: "+212",
    country: "Western Sahara",
    short: "EH",
    flag: "🇪🇭",
    minLength: 9,
    maxLength: 9,
  },

  // Y
  {
    code: "+967",
    country: "Yemen",
    short: "YE",
    flag: "🇾🇪",
    minLength: 9,
    maxLength: 9,
  },

  // Z
  {
    code: "+260",
    country: "Zambia",
    short: "ZM",
    flag: "🇿🇲",
    minLength: 9,
    maxLength: 9,
  },
  {
    code: "+263",
    country: "Zimbabwe",
    short: "ZW",
    flag: "🇿🇼",
    minLength: 9,
    maxLength: 9,
  },
];

export default countryCodes;
